CREATE DATABASE ERP_IMPACTA;

USE PEDIDOS;

--criando a View
GO 
CREATE VIEW VIE_EMPREGADO AS 
SELECT CODFUN, NOME, DATA_ADMISSAO, COD_DEPTO, COD_CARGO, SALARIO
FROM TB_EMPREGADO
GO


SELECT * FROM VIE_EMPREGADO

SELECT CODFUN, NOME FROM VIE_EMPREGADO





CREATE FUNCTION FN_MAIOR (@N1 INT, @N2 INT)
RETURNS INT
AS BEGIN
DECLARE @RET INT;
IF @N1 > @N2
	SET @RET = @N1;
ELSE
	SET @RET = @N2;
RETURN (@RET)
END
GO

--TESTANDO

SELECT DBO.FN_MAIOR(5,3)
SELECT DBO.FN_MAIOR(7,11)