use AdventureWorksDW2016_EXT;

select * from DimProduct
select * from DimAccount
select * from DimCurrency
select * from DimDepartmentGroup
select * from DimEmployee
select * from DimGeography
select * from DimProductCategory
select * from DimProductSubcategory
select * from DimPromotion
select * from DimReseller
select * from DimSalesReason
select * from DimSalesTerritory
select * from DimScenario
select * from FactAdditionalInternationalProductDescription
select * from FactCallCenter
select * from FactCurrencyRate
select * from FactFinance
select * from FactInternetSales
select * from FactInternetSalesReason
select count(*) from FactInternetSalesReason
select * from FactProductInventory
select * from FactResellerSales
select * from FactResellerSalesXL_CCI
select count(*) from FactResellerSalesXL_CCI
select * from FactResellerSalesXL_PageCompressed
select count(*) from FactResellerSalesXL_PageCompressed
select * from FactSalesQuota
select * from FactSurveyResponse
select * from NewFactCurrencyRate
select * from ProspectiveBuyer